// Phase1D-2 bus_events_catalog event_code literals.
// Canonical metadata is persisted in bus_events_catalog and seeded by jl-api/migrations/2012_seed_bus_events_catalog*.sql.
// Keep these literals aligned with CODEX/vocab/vocab.tsv rows domain=bus_events.catalog attribute=event_code until vocab-driven generation is introduced.

export const BUS_EVENT_CODES = {
  AUTO_FINALIZE_ACK: "AUTO_FINALIZE_ACK",
  BUS_RECOVERY_START: "BUS_RECOVERY_START",
  BUS_STALL_CLEARED: "BUS_STALL_CLEARED",
  BUS_STALL_DETECTED: "BUS_STALL_DETECTED",
  BUS_STALL_NOT_CLEARED: "BUS_STALL_NOT_CLEARED",
  CLAIM_RECLAIMED: "CLAIM_RECLAIMED",
  DISPATCH_DELIVERY_FAILED: "DISPATCH_DELIVERY_FAILED",
  DISPATCH_DELIVERY_SUCCEEDED: "DISPATCH_DELIVERY_SUCCEEDED",
  DISPATCH_REQUESTED: "DISPATCH_REQUESTED",
  DISPATCH_ROUTE_DISABLED: "DISPATCH_ROUTE_DISABLED",
  DISPATCH_ROUTE_NOT_FOUND: "DISPATCH_ROUTE_NOT_FOUND",
  ECHO_REQUEST_NOT_FOUND: "ECHO_REQUEST_NOT_FOUND",
  ENQUEUE_CONSTRAINT_FAILED: "ENQUEUE_CONSTRAINT_FAILED",
  ENQUEUE_DUPLICATE: "ENQUEUE_DUPLICATE",
  ENQUEUE_PRECHECK_REJECTED: "ENQUEUE_PRECHECK_REJECTED",
  LANE_MISMATCH: "LANE_MISMATCH",
  MISSING_ECHO_REQUEST_BUS_ID: "MISSING_ECHO_REQUEST_BUS_ID",
  PROPOSAL_REF_ALREADY_CONSUMED: "PROPOSAL_REF_ALREADY_CONSUMED",
  PROPOSAL_REF_FLOW_OWNER_MISMATCH: "PROPOSAL_REF_FLOW_OWNER_MISMATCH",
  PROPOSAL_REF_LANE_MISMATCH: "PROPOSAL_REF_LANE_MISMATCH",
  PROPOSAL_REF_NOT_FOUND: "PROPOSAL_REF_NOT_FOUND",
  PROPOSAL_REF_ORIGIN_REQUEST_INVALID: "PROPOSAL_REF_ORIGIN_REQUEST_INVALID",
  PROPOSAL_REF_REQUEST_ID_MISMATCH: "PROPOSAL_REF_REQUEST_ID_MISMATCH",
  PROPOSAL_REF_TARGET_NOT_RESPONSE: "PROPOSAL_REF_TARGET_NOT_RESPONSE",
  PROPOSAL_REF_TARGET_OP_MISMATCH: "PROPOSAL_REF_TARGET_OP_MISMATCH",
  PROPOSAL_REF_TARGET_TERMINAL_MISMATCH: "PROPOSAL_REF_TARGET_TERMINAL_MISMATCH",
  REQUEST_ID_MISMATCH: "REQUEST_ID_MISMATCH",
} as const;

export type BusEventCode = typeof BUS_EVENT_CODES[keyof typeof BUS_EVENT_CODES];
