import { TRANSPORT_OPERATION_CATALOG } from "./transport_operation_catalog";

export const ROUTE_PATHS = {
  PING: TRANSPORT_OPERATION_CATALOG.PING.route_path,
  ENQUEUE: TRANSPORT_OPERATION_CATALOG.ENQUEUE.route_path,
  DEQUEUE: TRANSPORT_OPERATION_CATALOG.DEQUEUE.route_path,
  FINALIZE: TRANSPORT_OPERATION_CATALOG.FINALIZE.route_path,
  INBOX_POLL: TRANSPORT_OPERATION_CATALOG.INBOX_POLL.route_path,
  INBOX_TAKE: TRANSPORT_OPERATION_CATALOG.INBOX_TAKE.route_path,
  INBOX_ACK: TRANSPORT_OPERATION_CATALOG.INBOX_ACK.route_path,
  LOGS_TSV: TRANSPORT_OPERATION_CATALOG.LOGS_TSV_EXPORT.route_path,
  LOGS_TXT: TRANSPORT_OPERATION_CATALOG.LOGS_TXT_EXPORT.route_path,
  DEBUG_TXT: TRANSPORT_OPERATION_CATALOG.DEBUG_TXT_EXPORT.route_path,
  EVENTS_TXT: TRANSPORT_OPERATION_CATALOG.EVENTS_TXT_EXPORT.route_path,
} as const;

export type HttpRoutePath = typeof ROUTE_PATHS[keyof typeof ROUTE_PATHS];

export const TRANSPORT_OPERATIONS = {
  PING: TRANSPORT_OPERATION_CATALOG.PING.name,
  ENQUEUE: TRANSPORT_OPERATION_CATALOG.ENQUEUE.name,
  DEQUEUE: TRANSPORT_OPERATION_CATALOG.DEQUEUE.name,
  FINALIZE: TRANSPORT_OPERATION_CATALOG.FINALIZE.name,
  INBOX_POLL: TRANSPORT_OPERATION_CATALOG.INBOX_POLL.name,
  INBOX_TAKE: TRANSPORT_OPERATION_CATALOG.INBOX_TAKE.name,
  INBOX_ACK: TRANSPORT_OPERATION_CATALOG.INBOX_ACK.name,
  LOGS_TSV_EXPORT: TRANSPORT_OPERATION_CATALOG.LOGS_TSV_EXPORT.name,
  LOGS_TXT_EXPORT: TRANSPORT_OPERATION_CATALOG.LOGS_TXT_EXPORT.name,
  DEBUG_TXT_EXPORT: TRANSPORT_OPERATION_CATALOG.DEBUG_TXT_EXPORT.name,
  EVENTS_TXT_EXPORT: TRANSPORT_OPERATION_CATALOG.EVENTS_TXT_EXPORT.name,
} as const;

export type TransportOperation =
  typeof TRANSPORT_OPERATIONS[keyof typeof TRANSPORT_OPERATIONS];

export const KNOWN_ROUTE_PATHS = new Set<string>([
  ROUTE_PATHS.PING,
  ROUTE_PATHS.ENQUEUE,
  ROUTE_PATHS.DEQUEUE,
  ROUTE_PATHS.FINALIZE,
  ROUTE_PATHS.INBOX_POLL,
  ROUTE_PATHS.INBOX_TAKE,
  ROUTE_PATHS.INBOX_ACK,
]);
