-- DDL_D1_74_seed_bus_events_catalog.sql
-- Seed bus_events_catalog with event_code definitions materialized from vocab preview.
-- Source of truth (canonical): CODEX/vocab/bus_events_catalog_seed_preview.tsv
-- Target: Cloudflare D1 (SQLite)

INSERT OR IGNORE INTO bus_events_catalog(
  event_code,severity,default_scope_kind,recovery_profile,
  required_data_keys,optional_data_keys,message_template
) VALUES
  ('AUTO_FINALIZE_ACK','INFO','BUS_MESSAGE','AUTO_FINALIZE','["q_state", "reason"]','["criteria.match.claim_age_sec_gt", "criteria.match.in_state", "criteria.match.lane_id", "criteria.match.msg_type", "criteria.match.state", "criteria.match.to_owner_id", "criteria.target_q_state", "dry_run", "incident_id", "sample_bus_ids", "transition.q_state.from", "transition.q_state.to", "transition.done_at.from", "transition.done_at.to"]','Auto-finalize ACK executed safely for one message (bus_id).'),
  ('BUS_RECOVERY_START','INFO','OWNER',NULL,'["incident_id", "plan.strategy", "recovery_profile", "scope_kind", "scope_owner_id"]','["plan.criteria", "plan.dry_run", "scope_lane_id", "started_by"]','Recovery started for incident_id={incident_id} profile={recovery_profile}.'),
  ('BUS_STALL_CLEARED','INFO','OWNER',NULL,'["duration_ms", "incident_id", "manual_required", "metrics_after.oldest_age_sec", "metrics_after.pending_count", "metrics_before.oldest_age_sec", "metrics_before.pending_count", "recovery_profile", "scope_kind", "scope_owner_id"]','["dead_count", "done_count", "finalized_count", "notes"]','Stall cleared for incident_id={incident_id}.'),
  ('BUS_STALL_DETECTED','WARN','OWNER',NULL,'["detected_by", "incident_id", "metrics.oldest_age_sec", "metrics.pending_count", "scope_kind", "scope_owner_id", "thresholds.oldest_age_sec", "thresholds.pending_count"]','["evidence.query_id", "evidence.sample_bus_ids", "metrics.claim_stuck_count", "scope_lane_id", "thresholds.claim_stuck_count"]','Bus stall detected for scope={scope_kind}:{scope_owner_id}{:scope_lane_id}.'),
  ('BUS_STALL_NOT_CLEARED','ERROR','OWNER',NULL,'["duration_ms", "incident_id", "manual_required", "metrics_after.oldest_age_sec", "metrics_after.pending_count", "metrics_before.oldest_age_sec", "metrics_before.pending_count", "recovery_profile", "scope_kind", "scope_owner_id"]','["error_summary", "next_action", "notes"]','Stall NOT cleared for incident_id={incident_id}; manual_required={manual_required}.'),
  ('CLAIM_RECLAIMED','WARN','BUS_MESSAGE',NULL,'[]','["claim.claimed_at", "claim.claimed_by", "claim.expired_at", "reason", "transition.claimed_by.from", "transition.claimed_by.to", "transition.claimed_at.from", "transition.claimed_at.to"]','TTL reclaim cleared an expired claim for bus_id={bus_id} (claim fields may have been overwritten)'),
  ('ECHO_REQUEST_NOT_FOUND','ERROR','BUS_MESSAGE',NULL,'[]','["response_bus_id", "response_from_owner_id", "response_to_owner_id", "response_flow_owner_id", "response_lane_id", "response_request_id", "echo_request_bus_id", "request_bus_id", "request_bus_ts", "request_flow_owner_id", "request_lane_id", "request_id"]','RESPONSE echo_request_bus_id not found in bus_messages'),
  ('ENQUEUE_CONSTRAINT_FAILED','ERROR','BUS_MESSAGE',NULL,'[]','["constraint", "lane_id", "reason", "request_id", "to_owner_id"]','enqueue failed by DB constraint (non-duplicate): bus_id={bus_id}'),
  ('ENQUEUE_DUPLICATE','WARN','BUS_MESSAGE',NULL,'[]','["lane_id", "reason", "request_id", "to_owner_id"]','enqueue ignored because bus_id already exists (idempotent duplicate): bus_id={bus_id}'),
  ('LANE_MISMATCH','ERROR','BUS_MESSAGE',NULL,'[]','["response_bus_id", "response_from_owner_id", "response_to_owner_id", "response_flow_owner_id", "response_lane_id", "response_request_id", "echo_request_bus_id", "request_bus_id", "request_bus_ts", "request_flow_owner_id", "request_lane_id", "request_id"]','RESPONSE lane_id does not match REQUEST lane_id referenced by echo_request_bus_id'),
  ('MISSING_ECHO_REQUEST_BUS_ID','ERROR','BUS_MESSAGE',NULL,'[]','["response_bus_id", "response_from_owner_id", "response_to_owner_id", "response_flow_owner_id", "response_lane_id", "response_request_id", "echo_request_bus_id", "request_bus_id", "request_bus_ts", "request_flow_owner_id", "request_lane_id", "request_id"]','RESPONSE is missing contentsmetaecho_request_bus_id'),
  ('REQUEST_ID_MISMATCH','ERROR','BUS_MESSAGE',NULL,'[]','["response_bus_id", "response_from_owner_id", "response_to_owner_id", "response_flow_owner_id", "response_lane_id", "response_request_id", "echo_request_bus_id", "request_bus_id", "request_bus_ts", "request_flow_owner_id", "request_lane_id", "request_id"]','RESPONSE request_id does not match REQUEST request_id referenced by echo_request_bus_id');
